version: "3"
services:
  nginx:
    container_name: php_nginx
    build: ./.docker/nginx
    ports:
      - 80:80
    # volumes:
      # - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./:/usr/share/nginx/html
  app:
    container_name: php_app
    build: ./.docker/php
    ports:
      - 8000:8000
    volumes:
      - ./:/workspace

  db:
    container_name: php_mysql
    build: ./.docker/mysql
    ports:
      - 3306:3306
    volumes:
      - laravel_db_volume:/var/lib/mysql
      # - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  laravel_db_volume:
